### ISSUE TITLE
Slides require password

### ISSUE THREAD

**Issue by francishero** [sdras/intro-to-vue#1]
Please provide the password to view slides

**Comment by denbatte** [comment]
Please scan trough the readme and the password will be there.

!vue!

**Comment by elhanarinc** [comment]
it says wrong password for *!vue!*

**Comment by sdras** [comment]
I just went through and checked all of them in another browser, they seem to be working fine, can you please give me a little more detail about what's not working for you? Which deck, and are you sure you're typing !vue!  ? Thanks

**Comment by elhanarinc** [comment]
I have checked every link with chrome browser and noone seems to be working with !vue! password.

**Comment by sdras** [comment]
Hm, that's so strange, let me see if I can borrow another machine and test because I can't duplicate in any browser. Stay tuned. What OS are you on?

**Comment by melniker** [comment]
I can confirm that the passwd worked for me for deck 1. 

Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/59.0.3071.102 Mobile/14F89 Safari/602.1

**Comment by elhanarinc** [comment]
I am using win 10 education with chrome 59.0.3071.115 version 64bit. 
Thanks !

**Comment by sdras** [comment]
wat.

OK I just tried on chrome (same version) with win 10 home and it's loading ok- sorry to make you do this but could you try deleting cookies and hard refreshing and try again?

**Comment by elhanarinc** [comment]
I found the problem. I am using *HTTPS Everywhere* extension with my chrome so it checks the website served with HTTPS and if it not extension does not load the website.
Disabling it gave me the slides. 
![](https://media.giphy.com/media/3osxYlhbYjOIDEZhkI/giphy.gif)

**Comment by sdras** [comment]
Awesome, I was hoping it was something like that. Closing this out. 🤘🏼

**Comment by TheInternerd12** [comment]
@sdras could you add this as a side note to the README? Would be awesome, thx 👍
