### ISSUE TITLE
404 when trying to access the code pen for challenge 6

### ISSUE THREAD

**Issue by mmudge** [sdras/intro-to-vue#12]
Just letting you know I'm getting a 404 when trying to access the link to codepen  for challenge 6 from the top of the [slides](http://slides.com/sdrasner/intro-to-vue-6).

**Comment by cdvillard** [comment]
I don't believe there is a CodePen for the Filters, Mixins, and Custom Directives challenge. At least not in her [Intro to Vue collection](https://codepen.io/collection/noYZxW/) on CodePen. Given how she's on top of adding the CodePens for this workshop, I imagine this was supposed to be a standalone exercise.

**Comment by cdvillard** [comment]
Excuse me, @mmudge, I do take that back. It appears that it should be on CodePen. It seems to work for me, so if you're still having this issue, I've made [a clone of the problem CodePen in question](https://codepen.io/cdvillard/pen/pBXWvb). Here's [a link to the original](https://codepen.io/sdras/pen/d7ff124563d8f6226eb6cf0b2bb3a7a6) just in case.

**Comment by sdras** [comment]
Looks like this is solved for now, and I'm updating all materials and making new exercises for Vue 3 coming up soon, so it will be a new codepen for that exercise :)

**Comment by cdvillard** [comment]
Exciting! Thank you!
