### ISSUE TITLE
Add to awesome

### ISSUE THREAD

**Issue by nickmessing** [sdras/intro-to-vue#2]
Hey, I highly recommend adding this repo to [awesome-vue](https://github.com/vuejs/awesome-vue). A lot of people monitor changes over there and this is great resource to get familiar with vuejs.

**Comment by sdras** [comment]
oh, good call!

**Comment by nickmessing** [comment]
Ping @sdras? I'm still waiting for your PR, this looks like one of the best learning materials for vue available :smile:

**Comment by sdras** [comment]
I'm heads down on some client work right now, but I plan to get to it sometime this week!

**Comment by sdras** [comment]
🎉
