### ISSUE TITLE
installation error for nuxt sample

### ISSUE THREAD

**Issue by frazerwilson2** [sdras/intro-to-vue#5]
When running the npm run dev to setup the nuxt 'setup2' project, i receive this error:

``` ERROR  Failed to compile with 1 errors                                 08:59:29
This dependency was not found:
* ~components/Child.vue in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["/Users/frazer.wilson/intro-to-vue/setup2/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue

To install it, you can run: npm install --save ~components/Child.vue
```
If i run the command it suggests
```
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

**Comment by cdvillard** [comment]
@frazerwilson2 Not sure if you're still interested in this or just plain gave up, but as far as I can tell, your `~` is already set to a home path. When compiled, the system is reading it as literally, `Go to the home path, find the components directory, and find a file named Child.vue`. If you change the path to a relative one of `./../components/Child.vue` you should have success building the page.

**Comment by sdras** [comment]
Thanks to @cdvillard this is fixed.
