### ISSUE TITLE
Typo on Intro to Vue 1

### ISSUE THREAD

**Issue by arufian** [sdras/intro-to-vue#7]
Thanks for your great works on the slide introduction into VueJS.
It really helped me learning Vue.

There is a typo inside [intro to vue-1/slide number 35](http://slides.com/sdrasner/intro-to-vue-1?token=9-aFNhlX#/35).

It should be `stopPropagation` not `stopPropogation` (CMIIW)

**Comment by sdras** [comment]
Fixed!
